name: Build and Deploy SafirOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install NASM
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm

      - name: Prepare site
        run: |
          mkdir -p site
          cp index.html site/index.html

      - name: Build SafirOS
        run: |
          nasm -f bin boot/boot.asm -o site/SafirOS.img

      - name: Check image
        run: |
          ls -lh site/SafirOS.img
          test "$(stat -c%s site/SafirOS.img)" -eq 512

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
